### ISSUE TITLE
panic: sql: Register called twice for driver mysql

### ISSUE THREAD

**Issue by nicksrandall** [jargv/mig#1]
👋  Jon!

I'm running into an issue where mig is explicitly listing `github.com/go-sql-driver/mysql` as a dependency and so is another lib we are using (magma) and apparently you can only have one instance of a driver per app.

Here is the error I get: 
```
panic: sql: Register called twice for driver mysql
```

To me, it seems like (if only one instance can live in an app) that the app should be the one to explicitly list it as a dependency and no library should explicitly require it (so that you COULD have two libs that both use the driver). 

In the case of mig, you are explicitly using this package so I don't know how that could actually work. 

Let me know what you think about this and I'll be happy to send you a PR.

**Comment by jargv** [comment]
Hey Nick! 

Yeah it shouldn't be bringing in mysql directly. I thought it only did that for the tests... I can take a look tonight.
